# -*- coding: utf-8 -*-
"""DS323_Predicting_Road_Accidents_Severity_using_ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZvVjsWMChqnRQ5Ou00InE_sEtpFIN4yb

### **Predicting Road Accident Severity Based on Environmental and Driver Factors**

*   Jenan al kasi - 445008540
*   Meshael Alsemari - 445008576
*   Haifa Al Anazi - 445009402
*   Leen AlQuwayfil - 445008611

### **Imports**
"""

# Import required libraries
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn import preprocessing
from sklearn.model_selection import cross_val_score
import numpy as np

"""### **Load Raw Data**"""

from google.colab import files
# upload "traffic.csv"
uploaded = files.upload()

# Load dataset
data = pd.read_csv('traffic.csv')
data.head()

"""### **Data Understanding and EDA**"""

# Print out the number of rows and columns for your data
data.shape

data.info()

# Check for missing values
data.isnull().sum()

# Box plot to detect outliers in the number of vehicles involved
data[['Number_of_vehicles_involved']].plot.box()
plt.show()

# Print out the number of data for target feature (Accident_severity)
data['Accident_severity'].value_counts()

x1 = data['Accident_severity']
# histogram plot
plt.hist(x1)
plt.show()

"""The distribution of accident severity shows that most accidents are classified as slight injuries, while fatal accidents are less frequent."""

data['Weather_conditions'].value_counts()

"""Normal weather has the highest number of accidents since it is the most common condition, not necessarily the most dangerous."""

data['Type_of_vehicle'].value_counts()

"""Most accidents involve automobiles, likely because they represent the most common type of vehicle on the road."""

data['Cause_of_accident'].value_counts()

"""The most common causes of accidents are lack of distancing and lane changes, indicating that driver behavior plays a major role."""

plt.figure(figsize=(12,6))

sns.countplot(x='Cause_of_accident', hue='Accident_severity', data=data)

plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(12,6))

sns.countplot(x='Type_of_vehicle', hue='Accident_severity', data=data)

plt.xticks(rotation=45)
plt.show()

"""### **Load Clean Data**"""

from google.colab import files
# "traffic_copy.csv"
uploaded = files.upload()

data2 = pd.read_csv('traffic_copy.csv')
data2.head(10)

data2.shape

data2.info()

"""### **4. Data Modeling**"""

# Setting the features (X) and target (y)

X = data2.iloc[:, :-1].values
y = data2.iloc[:, 37].values

# Splitting data into train and test sets.
# The code will split the dataset into 90% training data and 10% of testing data, using random_state=0, and stratify=y
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42, stratify=y)

"""
## SVM Model"""

from sklearn import svm
SVC = svm.SVC()
#Fitting the model
SVC.fit(X_train, y_train)

# Making prediction on the training and testing sets of the model
predSVC_T = SVC.predict(X_train)
predSVC = SVC.predict(X_test)

# Printing the training and testing accuracy
print('Training Accuracy : ', accuracy_score(y_train,predSVC_T))
print('Test Accuracy : ', accuracy_score(y_test, predSVC))

""":**Model Performance accuracy in Predicting Road Accidents Severity interpretation:**

Phenomenon: Training Accuracy      ,       Test/Validation Accuracy

Training Accuracy: 84.9%          , Test Accuracy: 85%

Underfitting: The model does not show strong underfitting because both training and testing accuracies are relatively high.

Overfitting: There is no significant overfitting since the training and testing accuracies are very close.

Optimal Fit: The model appears stable, but the confusion matrix shows that it is biased toward predicting only class 0. This indicates poor performance in identifying other accident severity classes despite the high accuracy score.




"""

# Visualizing the confusion matrix by using heatmap
result = confusion_matrix(y_test, predSVC)

sns.heatmap(result, annot=True ,fmt="g")
plt.xlabel('Predicted labels')
plt.ylabel('True labels')
plt.show()

"""**Interpretation of the confusion matrix**

The model predicted all samples as class 0 only.

TN: 255 correctly classified samples for class 0. (Slight injury)

TP: 0 true positive predictions for classes 1 and 2.

FP: 45 samples were incorrectly predicted as class 0 (41 from class 1 and 4 from class 2).

FN: All actual class 1 and class 2 samples were missed by the model.

"""

# Classifcation Report
CR = classification_report(y_test, predSVC)
print("Classification Report:")
print (CR)

"""## Random Forest Model"""

from sklearn.ensemble import RandomForestClassifier

RF = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight='balanced'
)

# Fitting the model
RF.fit(X_train, y_train)

#Making Predictions
predRF_t = RF.predict(X_train)
predRF = RF.predict(X_test)

#Accuracy
print('Training Accuracy : ', accuracy_score(y_train, predRF_t))
print('Test Accuracy : ', accuracy_score(y_test, predRF))

"""## Model Performance accuracy in Predicting Road Accidents Severity interpretation

**Phenomenon:** Training Accuracy, Test/Validation Accuracy

### Underfitting:
The model does not show underfitting because both training and testing accuracy are relatively high.
### Overfitting:
There is slight overfitting because the training accuracy (98%) is higher than the testing accuracy (83%).

### Optimal Fit:
The Random Forest model achieved good performance in predicting road accident severity with acceptable generalization.
"""

result = confusion_matrix(y_test, predRF)

sns.heatmap(result, annot=True ,fmt="g")
plt.xlabel('Predicted labels')
plt.ylabel('True labels')
plt.show()

CR = classification_report(y_test, predRF, zero_division=0)

print("Classification Report:")
print(CR)

"""## Logistic Regression Model"""

from sklearn.linear_model import LogisticRegression
#Fitting the model
LR = LogisticRegression()
LR.fit(X_train, y_train)

#Making Predictions

predLR_Train = LR.predict(X_train)
predLR_Test = LR.predict(X_test)

# Accuracy
print('Training Accuracy : ', accuracy_score(y_train,predLR_Train))
print('Test Accuracy : ', accuracy_score(y_test, predLR_Test))

"""**Model Performance accuracy in Predicting Road Accidents Severity interpretation:**

**Training Accuracy:** 85% , **Test Accuracy:** 85%

**Underfitting:** The model does not show underfitting because both training and testing accuracies are relatively high.

**Overfitting:** There is no significant overfitting since the training and testing accuracies are very close to each other.

**Optimal Fit:** The model appears stable with consistent training and test accuracy. However, the confusion matrix reveals that the model predicted all samples as class 0 (Slight Injury), failing to identify any Serious Injury or Fatal Injury cases. This indicates that the high accuracy is misleading due to class imbalance.
"""

# Visualize the confusion matrix using heatmap

result = confusion_matrix(y_test, predLR_Test)

sns.heatmap(result, annot=True, cmap='crest', fmt="g", linewidth=2)
plt.xlabel('Predicted labels')
plt.ylabel('True labels')
plt.show()

"""**Confusion Matrix Interpretation:**


*   255 samples correctly classified as class 0 (Slight Injury)
*  0 true positive predictions for classes 1 and 2
*   41 Serious Injury and 4 Fatal Injury samples were all misclassified as class 0


"""

# Print Classifcation Report

CR = classification_report(y_test, predLR_Test)
print("Classification Report:",)
print (CR)

"""## **5. Scaling**"""

mm_scaler = preprocessing.MinMaxScaler()
X_mm = mm_scaler.fit_transform(X)

X_train2, X_test2, y_train2, y_test2 = train_test_split(X_mm, y, test_size=0.1, random_state=42)

rf2 = RandomForestClassifier(random_state=42)
rf2.fit(X_train2, y_train2)

y_train_pred2 = rf2.predict(X_train2)
y_pred2 = rf2.predict(X_test2)

print('Training Accuracy after Pre-processing using MinMaxScaler:', accuracy_score(y_train2, y_train_pred2))
print('Test Accuracy after Pre-processing using MinMaxScaler:', accuracy_score(y_test2, y_pred2))

from sklearn.model_selection import cross_val_score
import numpy as np

best_score = 0

for n_est in [50, 100, 150]:
    for depth in [5, 10, 15]:

        model = RandomForestClassifier(n_estimators=n_est, max_depth=depth, random_state=42)
        scores = cross_val_score(model, X_train2, y_train2, cv=5)
        score = np.mean(scores)

        if score > best_score:
            best_score = score
            best_params = {'n_estimators': n_est, 'max_depth': depth}

print(f"Best score found: {best_score:.4f}")
print(f"Best parameters: {best_params}")

final_rf = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
final_rf.fit(X_train2, y_train2)
print("Training Accuracy after Tuning:", final_rf.score(X_train2, y_train2))
print("Final Test Accuracy:", final_rf.score(X_test2, y_test2))



"""# **6. Evaluation**"""

import joblib
joblib.dump(final_rf, 'final_rf.pkl')
joblib.dump(mm_scaler, 'mm_scaler.pkl')
from google.colab import files
files.download('final_rf.pkl')
files.download('mm_scaler.pkl')

final_rf = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    random_state=42,
    class_weight='balanced'  # ← this fixes the bias
)
final_rf.fit(X_train2, y_train2)

joblib.dump(final_rf, 'final_rf.pkl')
from google.colab import files
files.download('final_rf.pkl')

